-- Remote Supabase migration history exportundan yeniden oluşturuldu.
-- Version: 20260712010000
-- Name: v2_8_0_content_shares
-- Bu dosyanın version/name değeri remote schema_migrations kaydıyla eşleşmelidir.

-- Statement 1/32
-- Bizim Mekanlar v2.8.0
-- In-app content sharing for places, notes, collections and profiles.

begin;

-- Statement 2/32
create table if not exists public."ContentShares" (
  "ContentShareId" bigint generated by default as identity primary key,
  "SenderUserId" integer not null references public."Users"("UserId"),
  "RecipientUserId" integer not null references public."Users"("UserId"),
  "ShareTypeCode" varchar(20) not null,
  "PlaceId" integer null,
  "PlaceNoteId" integer null,
  "UserPlaceListId" bigint null,
  "ProfileUserId" integer null,
  "Message" varchar(100) null,
  "TargetTitle" varchar(180) not null,
  "TargetSubtitle" varchar(220) null,
  "TargetPublicId" uuid null,
  "TargetUsername" varchar(30) null,
  "IsRead" boolean not null default false,
  "ReadDate" timestamptz null,
  "PushSentDate" timestamptz null,
  "IsActive" boolean not null default true,
  "CreatedDate" timestamptz not null default now(),
  "UpdatedDate" timestamptz null,
  constraint "CK_ContentShares_DifferentUsers"
    check ("SenderUserId" <> "RecipientUserId"),
  constraint "CK_ContentShares_Type"
    check ("ShareTypeCode" in ('PLACE', 'NOTE', 'COLLECTION', 'PROFILE')),
  constraint "CK_ContentShares_Target"
    check (
      ("ShareTypeCode" = 'PLACE' and "PlaceId" is not null and "PlaceNoteId" is null and "UserPlaceListId" is null and "ProfileUserId" is null)
      or ("ShareTypeCode" = 'NOTE' and "PlaceId" is null and "PlaceNoteId" is not null and "UserPlaceListId" is null and "ProfileUserId" is null)
      or ("ShareTypeCode" = 'COLLECTION' and "PlaceId" is null and "PlaceNoteId" is null and "UserPlaceListId" is not null and "ProfileUserId" is null)
      or ("ShareTypeCode" = 'PROFILE' and "PlaceId" is null and "PlaceNoteId" is null and "UserPlaceListId" is null and "ProfileUserId" is not null)
    )
);

-- Statement 3/32
create index if not exists "IX_ContentShares_RecipientCreated"
  on public."ContentShares" ("RecipientUserId", "CreatedDate" desc)
  where "IsActive" = true;

-- Statement 4/32
create index if not exists "IX_ContentShares_SenderCreated"
  on public."ContentShares" ("SenderUserId", "CreatedDate" desc)
  where "IsActive" = true;

-- Statement 5/32
create index if not exists "IX_ContentShares_RecipientUnread"
  on public."ContentShares" ("RecipientUserId", "IsRead", "CreatedDate" desc)
  where "IsActive" = true;

-- Statement 6/32
alter table public."ContentShares" enable row level security;

-- Statement 7/32
drop policy if exists "ContentShares_SelectParticipants" on public."ContentShares";

-- Statement 8/32
create policy "ContentShares_SelectParticipants"
on public."ContentShares"
for select
to authenticated
using (
  "SenderUserId" = public."GetMySessionUserId"()
  or "RecipientUserId" = public."GetMySessionUserId"()
);

-- Statement 9/32
revoke all on table public."ContentShares" from anon, authenticated;

-- Statement 10/32
grant select on table public."ContentShares" to authenticated, service_role;

-- Statement 11/32
grant all on table public."ContentShares" to service_role;

-- Statement 12/32
grant usage, select on all sequences in schema public to service_role;

-- Statement 13/32
create or replace function public."HasContentShareBlock"(
  p_first_user_id integer,
  p_second_user_id integer
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public."UserBlocks" b
    where b."IsActive" = true
      and (
        (b."BlockerUserId" = p_first_user_id and b."BlockedUserId" = p_second_user_id)
        or (b."BlockerUserId" = p_second_user_id and b."BlockedUserId" = p_first_user_id)
      )
  );
$$;

-- Statement 14/32
-- Earlier releases used more than one follow-status layout. This helper keeps
-- v2.8.0 compatible with those databases while preferring explicit accepted
-- status columns whenever they are available.
create or replace function public."HasAcceptedFollowRelation"(
  p_follower_user_id integer,
  p_following_user_id integer
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result boolean := false;
begin
  if p_follower_user_id is null or p_following_user_id is null then
    return false;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'UserFollows'
      and column_name = 'FollowStatusCode'
  ) then
    execute $query$
      select exists (
        select 1 from public."UserFollows" f
        where f."FollowerUserId" = $1
          and f."FollowingUserId" = $2
          and f."IsActive" = true
          and upper(coalesce(f."FollowStatusCode", '')) = 'ACCEPTED'
      )
    $query$ into v_result using p_follower_user_id, p_following_user_id;
    return coalesce(v_result, false);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'UserFollows'
      and column_name = 'StatusCode'
  ) then
    execute $query$
      select exists (
        select 1 from public."UserFollows" f
        where f."FollowerUserId" = $1
          and f."FollowingUserId" = $2
          and f."IsActive" = true
          and upper(coalesce(f."StatusCode", '')) = 'ACCEPTED'
      )
    $query$ into v_result using p_follower_user_id, p_following_user_id;
    return coalesce(v_result, false);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'UserFollows'
      and column_name = 'IsAccepted'
  ) then
    execute $query$
      select exists (
        select 1 from public."UserFollows" f
        where f."FollowerUserId" = $1
          and f."FollowingUserId" = $2
          and f."IsActive" = true
          and f."IsAccepted" = true
      )
    $query$ into v_result using p_follower_user_id, p_following_user_id;
    return coalesce(v_result, false);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'UserFollows'
      and column_name = 'FollowStatusId'
  ) and to_regclass('public."FollowStatuses"') is not null then
    execute $query$
      select exists (
        select 1
        from public."UserFollows" f
        join public."FollowStatuses" s
          on s."FollowStatusId" = f."FollowStatusId"
        where f."FollowerUserId" = $1
          and f."FollowingUserId" = $2
          and f."IsActive" = true
          and upper(coalesce(s."Code", '')) = 'ACCEPTED'
      )
    $query$ into v_result using p_follower_user_id, p_following_user_id;
    return coalesce(v_result, false);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'UserFollows'
      and column_name = 'UserFollowStatusId'
  ) and to_regclass('public."UserFollowStatuses"') is not null then
    execute $query$
      select exists (
        select 1
        from public."UserFollows" f
        join public."UserFollowStatuses" s
          on s."UserFollowStatusId" = f."UserFollowStatusId"
        where f."FollowerUserId" = $1
          and f."FollowingUserId" = $2
          and f."IsActive" = true
          and upper(coalesce(s."Code", '')) = 'ACCEPTED'
      )
    $query$ into v_result using p_follower_user_id, p_following_user_id;
    return coalesce(v_result, false);
  end if;

  -- Compatibility fallback for older schemas where active rows represented an
  -- accepted relationship and pending requests lived elsewhere.
  select exists (
    select 1
    from public."UserFollows" f
    where f."FollowerUserId" = p_follower_user_id
      and f."FollowingUserId" = p_following_user_id
      and f."IsActive" = true
  ) into v_result;

  return coalesce(v_result, false);
end;
$$;

-- Statement 15/32
create or replace function public."CanOpenContentShareTarget"(
  p_viewer_user_id integer,
  p_share_type_code text,
  p_place_id integer default null,
  p_place_note_id integer default null,
  p_user_place_list_id bigint default null,
  p_profile_user_id integer default null
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_type text := upper(trim(coalesce(p_share_type_code, '')));
  v_owner_user_id integer;
  v_account_visibility_code text;
  v_list_visibility_code text;
  v_is_collaborator boolean := false;
begin
  if not exists (
    select 1 from public."Users" viewer
    where viewer."UserId" = p_viewer_user_id
      and viewer."IsActive" = true
      and coalesce(viewer."AccountStatus", 'ACTIVE') = 'ACTIVE'
  ) then
    return false;
  end if;

  if v_type = 'PLACE' then
    return exists (
      select 1 from public."Places" p
      where p."PlaceId" = p_place_id and p."IsActive" = true
    );
  end if;

  if v_type = 'PROFILE' then
    return exists (
      select 1 from public."Users" target_user
      where target_user."UserId" = p_profile_user_id
        and target_user."IsActive" = true
        and coalesce(target_user."AccountStatus", 'ACTIVE') = 'ACTIVE'
    ) and not public."HasContentShareBlock"(p_viewer_user_id, p_profile_user_id);
  end if;

  if v_type = 'NOTE' then
    select note_row."UserId", upper(coalesce(visibility."Code", 'PRIVATE'))
    into v_owner_user_id, v_account_visibility_code
    from public."PlaceNotes" note_row
    join public."Users" owner_user
      on owner_user."UserId" = note_row."UserId"
     and owner_user."IsActive" = true
     and coalesce(owner_user."AccountStatus", 'ACTIVE') = 'ACTIVE'
    join public."AccountVisibilityStatuses" visibility
      on visibility."AccountVisibilityStatusId" = owner_user."AccountVisibilityStatusId"
     and visibility."IsActive" = true
    where note_row."PlaceNoteId" = p_place_note_id
      and note_row."IsActive" = true
    limit 1;

    if v_owner_user_id is null
       or public."HasContentShareBlock"(p_viewer_user_id, v_owner_user_id) then
      return false;
    end if;

    return p_viewer_user_id = v_owner_user_id
      or v_account_visibility_code = 'PUBLIC'
      or public."HasAcceptedFollowRelation"(p_viewer_user_id, v_owner_user_id);
  end if;

  if v_type = 'COLLECTION' then
    select
      list_row."UserId",
      upper(coalesce(list_row."VisibilityCode", 'PRIVATE')),
      upper(coalesce(visibility."Code", 'PRIVATE'))
    into
      v_owner_user_id,
      v_list_visibility_code,
      v_account_visibility_code
    from public."UserPlaceLists" list_row
    join public."Users" owner_user
      on owner_user."UserId" = list_row."UserId"
     and owner_user."IsActive" = true
     and coalesce(owner_user."AccountStatus", 'ACTIVE') = 'ACTIVE'
    join public."AccountVisibilityStatuses" visibility
      on visibility."AccountVisibilityStatusId" = owner_user."AccountVisibilityStatusId"
     and visibility."IsActive" = true
    where list_row."UserPlaceListId" = p_user_place_list_id
      and list_row."IsActive" = true
    limit 1;

    if v_owner_user_id is null
       or public."HasContentShareBlock"(p_viewer_user_id, v_owner_user_id) then
      return false;
    end if;

    if to_regclass('public."UserPlaceListCollaborators"') is not null then
      select exists (
        select 1
        from public."UserPlaceListCollaborators" collaborator
        where collaborator."UserPlaceListId" = p_user_place_list_id
          and collaborator."UserId" = p_viewer_user_id
          and collaborator."IsActive" = true
      ) into v_is_collaborator;
    end if;

    return p_viewer_user_id = v_owner_user_id
      or v_is_collaborator
      or (
        v_list_visibility_code = 'PUBLIC'
        and (
          v_account_visibility_code = 'PUBLIC'
          or public."HasAcceptedFollowRelation"(p_viewer_user_id, v_owner_user_id)
        )
      );
  end if;

  return false;
end;
$$;

-- Statement 16/32
create or replace function public."SendContentShare"(
  p_recipient_user_id integer,
  p_share_type_code text,
  p_place_id integer default null,
  p_place_note_id integer default null,
  p_user_place_list_id bigint default null,
  p_profile_user_id integer default null,
  p_message text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sender_user_id integer := public."GetMyActiveUserId"();
  v_type text := upper(trim(coalesce(p_share_type_code, '')));
  v_message text := nullif(trim(coalesce(p_message, '')), '');
  v_share_id bigint;
  v_title text;
  v_subtitle text;
  v_public_id uuid;
  v_username text;
begin
  if p_recipient_user_id is null or p_recipient_user_id = v_sender_user_id then
    raise exception 'Geçersiz alıcı.';
  end if;

  if v_type not in ('PLACE', 'NOTE', 'COLLECTION', 'PROFILE') then
    raise exception 'Geçersiz paylaşım türü.';
  end if;

  if char_length(coalesce(v_message, '')) > 100 then
    raise exception 'Kısa not en fazla 100 karakter olabilir.';
  end if;

  if not exists (
    select 1 from public."Users" recipient
    where recipient."UserId" = p_recipient_user_id
      and recipient."IsActive" = true
      and coalesce(recipient."AccountStatus", 'ACTIVE') = 'ACTIVE'
  ) then
    raise exception 'Alıcı kullanıcı bulunamadı.';
  end if;

  if public."HasContentShareBlock"(v_sender_user_id, p_recipient_user_id) then
    raise exception 'Bu kullanıcıya içerik gönderemezsin.';
  end if;

  if not exists (
    select 1
    from public."GetExternalUserProfile"(p_recipient_user_id) recipient_profile
    where recipient_profile."FollowStatusCode" = 'ACCEPTED'
  ) then
    raise exception 'Yalnızca takip ettiğin kullanıcılara içerik gönderebilirsin.';
  end if;

  if not public."CanOpenContentShareTarget"(
    v_sender_user_id,
    v_type,
    p_place_id,
    p_place_note_id,
    p_user_place_list_id,
    p_profile_user_id
  ) then
    raise exception 'Bu içeriği paylaşma yetkin yok.';
  end if;

  if not public."CanOpenContentShareTarget"(
    p_recipient_user_id,
    v_type,
    p_place_id,
    p_place_note_id,
    p_user_place_list_id,
    p_profile_user_id
  ) then
    raise exception 'Bu içerik alıcı tarafından görüntülenemiyor.';
  end if;

  if (
    select count(*)
    from public."ContentShares" share_row
    where share_row."SenderUserId" = v_sender_user_id
      and share_row."IsActive" = true
      and share_row."CreatedDate" >= now() - interval '1 hour'
  ) >= 20 then
    raise exception 'Çok fazla paylaşım yaptın. Biraz bekleyip tekrar dene.';
  end if;

  if (
    select count(*)
    from public."ContentShares" share_row
    where share_row."SenderUserId" = v_sender_user_id
      and share_row."RecipientUserId" = p_recipient_user_id
      and share_row."IsActive" = true
      and share_row."CreatedDate" >= now() - interval '10 minutes'
  ) >= 5 then
    raise exception 'Bu kullanıcıya kısa sürede çok fazla paylaşım yaptın.';
  end if;

  if exists (
    select 1
    from public."ContentShares" share_row
    where share_row."SenderUserId" = v_sender_user_id
      and share_row."RecipientUserId" = p_recipient_user_id
      and share_row."ShareTypeCode" = v_type
      and share_row."IsActive" = true
      and share_row."CreatedDate" >= now() - interval '5 minutes'
      and coalesce(share_row."PlaceId", 0) = coalesce(p_place_id, 0)
      and coalesce(share_row."PlaceNoteId", 0) = coalesce(p_place_note_id, 0)
      and coalesce(share_row."UserPlaceListId", 0) = coalesce(p_user_place_list_id, 0)
      and coalesce(share_row."ProfileUserId", 0) = coalesce(p_profile_user_id, 0)
  ) then
    raise exception 'Bu içeriği aynı kullanıcıya az önce gönderdin.';
  end if;

  if v_type = 'PLACE' then
    select p."Name"::text, 'Mekan'::text, p."PublicId"
    into v_title, v_subtitle, v_public_id
    from public."Places" p
    where p."PlaceId" = p_place_id and p."IsActive" = true;
  elsif v_type = 'NOTE' then
    select
      coalesce(nullif(trim(note_row."Title"), ''), 'Not')::text,
      place_row."Name"::text,
      note_row."PublicId"
    into v_title, v_subtitle, v_public_id
    from public."PlaceNotes" note_row
    left join public."Places" place_row on place_row."PlaceId" = note_row."PlaceId"
    where note_row."PlaceNoteId" = p_place_note_id and note_row."IsActive" = true;
  elsif v_type = 'COLLECTION' then
    select
      list_row."Name"::text,
      ('@' || owner_user."Username")::text,
      list_row."PublicId"
    into v_title, v_subtitle, v_public_id
    from public."UserPlaceLists" list_row
    join public."Users" owner_user on owner_user."UserId" = list_row."UserId"
    where list_row."UserPlaceListId" = p_user_place_list_id
      and list_row."IsActive" = true;
  else
    select
      ('@' || target_user."Username")::text,
      nullif(trim(concat_ws(' ', target_user."FirstName", target_user."LastName")), '')::text,
      target_user."Username"::text
    into v_title, v_subtitle, v_username
    from public."Users" target_user
    where target_user."UserId" = p_profile_user_id
      and target_user."IsActive" = true
      and coalesce(target_user."AccountStatus", 'ACTIVE') = 'ACTIVE';
  end if;

  if v_title is null then
    raise exception 'Paylaşılacak içerik bulunamadı.';
  end if;

  insert into public."ContentShares" (
    "SenderUserId",
    "RecipientUserId",
    "ShareTypeCode",
    "PlaceId",
    "PlaceNoteId",
    "UserPlaceListId",
    "ProfileUserId",
    "Message",
    "TargetTitle",
    "TargetSubtitle",
    "TargetPublicId",
    "TargetUsername",
    "IsRead",
    "IsActive",
    "CreatedDate"
  ) values (
    v_sender_user_id,
    p_recipient_user_id,
    v_type,
    case when v_type = 'PLACE' then p_place_id end,
    case when v_type = 'NOTE' then p_place_note_id end,
    case when v_type = 'COLLECTION' then p_user_place_list_id end,
    case when v_type = 'PROFILE' then p_profile_user_id end,
    v_message,
    left(v_title, 180),
    left(v_subtitle, 220),
    v_public_id,
    v_username,
    false,
    true,
    now()
  )
  returning "ContentShareId" into v_share_id;

  return v_share_id;
end;
$$;

-- Statement 17/32
create or replace function public."GetMyContentShares"(p_limit integer default 40)
returns table (
  "ContentShareId" bigint,
  "SenderUserId" integer,
  "SenderUsername" varchar,
  "SenderFirstName" varchar,
  "SenderLastName" varchar,
  "ShareTypeCode" varchar,
  "PlaceId" integer,
  "PlaceNoteId" integer,
  "UserPlaceListId" bigint,
  "ProfileUserId" integer,
  "Message" varchar,
  "TargetTitle" varchar,
  "TargetSubtitle" varchar,
  "TargetPublicId" uuid,
  "TargetUsername" varchar,
  "CanOpen" boolean,
  "IsRead" boolean,
  "CreatedDate" timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
  v_limit integer := least(greatest(coalesce(p_limit, 40), 1), 80);
begin
  return query
  select
    share_row."ContentShareId",
    sender."UserId",
    sender."Username"::varchar,
    sender."FirstName"::varchar,
    sender."LastName"::varchar,
    share_row."ShareTypeCode"::varchar,
    share_row."PlaceId",
    share_row."PlaceNoteId",
    share_row."UserPlaceListId",
    share_row."ProfileUserId",
    share_row."Message"::varchar,
    share_row."TargetTitle"::varchar,
    share_row."TargetSubtitle"::varchar,
    share_row."TargetPublicId",
    share_row."TargetUsername"::varchar,
    public."CanOpenContentShareTarget"(
      v_user_id,
      share_row."ShareTypeCode",
      share_row."PlaceId",
      share_row."PlaceNoteId",
      share_row."UserPlaceListId",
      share_row."ProfileUserId"
    ) as "CanOpen",
    share_row."IsRead",
    share_row."CreatedDate"
  from public."ContentShares" share_row
  join public."Users" sender
    on sender."UserId" = share_row."SenderUserId"
   and sender."IsActive" = true
   and coalesce(sender."AccountStatus", 'ACTIVE') = 'ACTIVE'
  where share_row."RecipientUserId" = v_user_id
    and share_row."IsActive" = true
    and not public."HasContentShareBlock"(v_user_id, share_row."SenderUserId")
    and share_row."CreatedDate" >= now() - interval '90 days'
  order by share_row."CreatedDate" desc
  limit v_limit;
end;
$$;

-- Statement 18/32
create or replace function public."MarkMyContentSharesRead"()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
begin
  update public."ContentShares"
  set "IsRead" = true,
      "ReadDate" = coalesce("ReadDate", now()),
      "UpdatedDate" = now()
  where "RecipientUserId" = v_user_id
    and "IsActive" = true
    and "IsRead" = false;
end;
$$;

-- Statement 19/32
-- Keep account deletion complete after v2.8.0 data is introduced.
create or replace function public."PurgeUserAccountData"(p_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public."Users" u
    where u."UserId" = p_user_id
      and u."AccountStatus" = 'DELETION_PENDING'
      and u."ScheduledDeletionDate" <= now()
  ) then
    raise exception 'Silinmeye hazır hesap bulunamadı.';
  end if;

  update public."ContentShares"
  set "IsActive" = false, "UpdatedDate" = now()
  where "SenderUserId" = p_user_id or "RecipientUserId" = p_user_id;

  update public."Notifications"
  set "IsActive" = false
  where "RecipientUserId" = p_user_id or "ActorUserId" = p_user_id;

  update public."UserFollows"
  set "IsActive" = false, "UpdatedDate" = now()
  where "FollowerUserId" = p_user_id or "FollowingUserId" = p_user_id;

  delete from public."UserMutes"
  where "MuterUserId" = p_user_id or "MutedUserId" = p_user_id;

  delete from public."UserBlocks"
  where "BlockerUserId" = p_user_id or "BlockedUserId" = p_user_id;

  if to_regclass('public."WebPushSubscriptions"') is not null then
    execute 'update public."WebPushSubscriptions" set "IsActive" = false, "UpdatedDate" = now() where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."UserWebPushPreferences"') is not null then
    execute 'delete from public."UserWebPushPreferences" where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."PlaceNoteReactions"') is not null then
    execute 'update public."PlaceNoteReactions" set "IsActive" = false, "UpdatedDate" = now() where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."UserPlaceListCollaborators"') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'UserPlaceListCollaborators'
         and column_name = 'UserId'
     ) then
    execute 'update public."UserPlaceListCollaborators" set "IsActive" = false where "UserId" = $1'
    using p_user_id;
  end if;

  update public."PlaceNotes"
  set "IsActive" = false, "UpdatedDate" = now()
  where "UserId" = p_user_id and "IsActive" = true;

  update public."UserPlaceLists"
  set "IsActive" = false, "UpdatedDate" = now()
  where "UserId" = p_user_id and "IsActive" = true;

  update public."Users"
  set "ProfilePhotoPath" = null,
      "DeletionAuthUserId" = coalesce("DeletionAuthUserId", "AuthUserId"),
      "AuthUserId" = null,
      "UpdatedDate" = now()
  where "UserId" = p_user_id;
end;
$$;

-- Statement 20/32
revoke all on function public."HasContentShareBlock"(integer, integer) from public;

-- Statement 21/32
revoke all on function public."HasAcceptedFollowRelation"(integer, integer) from public;

-- Statement 22/32
revoke all on function public."CanOpenContentShareTarget"(integer, text, integer, integer, bigint, integer) from public;

-- Statement 23/32
revoke all on function public."SendContentShare"(integer, text, integer, integer, bigint, integer, text) from public;

-- Statement 24/32
revoke all on function public."GetMyContentShares"(integer) from public;

-- Statement 25/32
revoke all on function public."MarkMyContentSharesRead"() from public;

-- Statement 26/32
revoke all on function public."PurgeUserAccountData"(integer) from public;

-- Statement 27/32
grant execute on function public."SendContentShare"(integer, text, integer, integer, bigint, integer, text) to authenticated;

-- Statement 28/32
grant execute on function public."GetMyContentShares"(integer) to authenticated;

-- Statement 29/32
grant execute on function public."MarkMyContentSharesRead"() to authenticated;

-- Statement 30/32
grant execute on function public."PurgeUserAccountData"(integer) to service_role;

-- Statement 31/32
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
       from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'ContentShares'
     ) then
    alter publication supabase_realtime add table public."ContentShares";
  end if;
end;
$$;

-- Statement 32/32
commit;
