-- Bizim Mekanlar v2.7.0
-- Settings center, block/mute controls, follower removal, account freeze and
-- seven-day deletion grace period.

begin;

alter table public."Users"
  add column if not exists "AccountStatus" varchar(24) not null default 'ACTIVE',
  add column if not exists "FrozenDate" timestamptz null,
  add column if not exists "DeletionRequestedDate" timestamptz null,
  add column if not exists "ScheduledDeletionDate" timestamptz null,
  add column if not exists "DeletionAuthUserId" uuid null;

-- The Auth reference must be detachable before deleting auth.users. The
-- original UUID is retained temporarily in DeletionAuthUserId for retries.
alter table public."Users"
  alter column "AuthUserId" drop not null;

update public."Users"
set "AccountStatus" = 'FROZEN',
    "FrozenDate" = coalesce("FrozenDate", "UpdatedDate", now())
where "IsActive" = false
  and "AuthUserId" is not null
  and coalesce("AccountStatus", 'ACTIVE') = 'ACTIVE';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'CK_Users_AccountStatus'
      and conrelid = 'public."Users"'::regclass
  ) then
    alter table public."Users"
      add constraint "CK_Users_AccountStatus"
      check ("AccountStatus" in ('ACTIVE', 'FROZEN', 'DELETION_PENDING', 'DELETED'));
  end if;
end;
$$;

create table if not exists public."UserBlocks" (
  "UserBlockId" bigint generated by default as identity primary key,
  "BlockerUserId" integer not null references public."Users"("UserId"),
  "BlockedUserId" integer not null references public."Users"("UserId"),
  "IsActive" boolean not null default true,
  "CreatedDate" timestamptz not null default now(),
  "UpdatedDate" timestamptz null,
  constraint "CK_UserBlocks_DifferentUsers"
    check ("BlockerUserId" <> "BlockedUserId")
);

create unique index if not exists "UX_UserBlocks_ActivePair"
  on public."UserBlocks" ("BlockerUserId", "BlockedUserId")
  where "IsActive" = true;

create index if not exists "IX_UserBlocks_BlockedUserId"
  on public."UserBlocks" ("BlockedUserId")
  where "IsActive" = true;

create table if not exists public."UserMutes" (
  "UserMuteId" bigint generated by default as identity primary key,
  "MuterUserId" integer not null references public."Users"("UserId"),
  "MutedUserId" integer not null references public."Users"("UserId"),
  "IsActive" boolean not null default true,
  "CreatedDate" timestamptz not null default now(),
  "UpdatedDate" timestamptz null,
  constraint "CK_UserMutes_DifferentUsers"
    check ("MuterUserId" <> "MutedUserId")
);

create unique index if not exists "UX_UserMutes_ActivePair"
  on public."UserMutes" ("MuterUserId", "MutedUserId")
  where "IsActive" = true;

create index if not exists "IX_UserMutes_MutedUserId"
  on public."UserMutes" ("MutedUserId")
  where "IsActive" = true;

alter table public."UserBlocks" enable row level security;
alter table public."UserMutes" enable row level security;

create or replace function public."EnforceUserFollowRelationshipRules"()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(new."IsActive", true) and exists (
    select 1
    from public."UserBlocks" b
    where b."IsActive" = true
      and ((b."BlockerUserId" = new."FollowerUserId" and b."BlockedUserId" = new."FollowingUserId")
        or (b."BlockerUserId" = new."FollowingUserId" and b."BlockedUserId" = new."FollowerUserId"))
  ) then
    raise exception 'Engellenmiş kullanıcıyla takip ilişkisi kurulamaz.';
  end if;

  return new;
end;
$$;

drop trigger if exists "TR_UserFollows_EnforceRelationshipRules"
on public."UserFollows";
create trigger "TR_UserFollows_EnforceRelationshipRules"
before insert or update of "FollowerUserId", "FollowingUserId", "IsActive"
on public."UserFollows"
for each row
execute function public."EnforceUserFollowRelationshipRules"();

create or replace function public."ClearMuteWhenFollowEnds"()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old."IsActive" = true and new."IsActive" = false then
    update public."UserMutes"
    set "IsActive" = false,
        "UpdatedDate" = now()
    where "MuterUserId" = old."FollowerUserId"
      and "MutedUserId" = old."FollowingUserId"
      and "IsActive" = true;
  end if;

  return new;
end;
$$;

drop trigger if exists "TR_UserFollows_ClearMuteWhenFollowEnds"
on public."UserFollows";
create trigger "TR_UserFollows_ClearMuteWhenFollowEnds"
after update of "IsActive"
on public."UserFollows"
for each row
execute function public."ClearMuteWhenFollowEnds"();

create or replace function public."ApplyNotificationRelationshipRules"()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not coalesce(new."IsActive", true)
     or new."RecipientUserId" is null
     or new."ActorUserId" is null then
    return new;
  end if;

  if exists (
    select 1
    from public."UserBlocks" b
    where b."IsActive" = true
      and ((b."BlockerUserId" = new."RecipientUserId" and b."BlockedUserId" = new."ActorUserId")
        or (b."BlockerUserId" = new."ActorUserId" and b."BlockedUserId" = new."RecipientUserId"))
  ) then
    new."IsActive" := false;
    return new;
  end if;

  if new."NotificationTypeCode" in (
      'FOLLOWING_NOTE',
      'NOTE_REACTION_UP',
      'NOTE_REACTION_DOWN'
    ) and exists (
      select 1
      from public."UserMutes" m
      where m."MuterUserId" = new."RecipientUserId"
        and m."MutedUserId" = new."ActorUserId"
        and m."IsActive" = true
    ) then
    new."IsActive" := false;
  end if;

  return new;
end;
$$;

drop trigger if exists "TR_Notifications_ApplyRelationshipRules"
on public."Notifications";
create trigger "TR_Notifications_ApplyRelationshipRules"
before insert or update of
  "RecipientUserId", "ActorUserId", "NotificationTypeCode", "IsActive"
on public."Notifications"
for each row
execute function public."ApplyNotificationRelationshipRules"();

create or replace function public."EnforceNoteReactionRelationshipRules"()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_note_owner_user_id integer;
begin
  if not coalesce(new."IsActive", true) then
    return new;
  end if;

  select note_row."UserId"
  into v_note_owner_user_id
  from public."PlaceNotes" note_row
  where note_row."PlaceNoteId" = new."PlaceNoteId"
  limit 1;

  if v_note_owner_user_id is not null and exists (
    select 1
    from public."UserBlocks" b
    where b."IsActive" = true
      and ((b."BlockerUserId" = v_note_owner_user_id and b."BlockedUserId" = new."UserId")
        or (b."BlockerUserId" = new."UserId" and b."BlockedUserId" = v_note_owner_user_id))
  ) then
    raise exception 'Engellenmiş kullanıcıyla not etkileşimi kurulamaz.';
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public."PlaceNoteReactions"') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'PlaceNoteReactions'
         and column_name in ('PlaceNoteId', 'UserId', 'IsActive')
       group by table_schema, table_name
       having count(*) = 3
     ) then
    execute 'drop trigger if exists "TR_PlaceNoteReactions_EnforceRelationshipRules" on public."PlaceNoteReactions"';
    execute 'create trigger "TR_PlaceNoteReactions_EnforceRelationshipRules" before insert or update of "PlaceNoteId", "UserId", "IsActive" on public."PlaceNoteReactions" for each row execute function public."EnforceNoteReactionRelationshipRules"()';
  end if;
end;
$$;

create or replace function public."EnforceCollectionCollaboratorRelationshipRules"()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_user_id integer;
begin
  if not coalesce(new."IsActive", true) then
    return new;
  end if;

  select l."UserId"
  into v_owner_user_id
  from public."UserPlaceLists" l
  where l."UserPlaceListId" = new."UserPlaceListId"
  limit 1;

  if v_owner_user_id is not null and exists (
    select 1
    from public."UserBlocks" b
    where b."IsActive" = true
      and ((b."BlockerUserId" = v_owner_user_id and b."BlockedUserId" = new."UserId")
        or (b."BlockerUserId" = new."UserId" and b."BlockedUserId" = v_owner_user_id))
  ) then
    raise exception 'Engellenmiş kullanıcı ortak listeye eklenemez.';
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public."UserPlaceListCollaborators"') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'UserPlaceListCollaborators'
         and column_name in ('UserPlaceListId', 'UserId', 'IsActive')
       group by table_schema, table_name
       having count(*) = 3
     ) then
    execute 'drop trigger if exists "TR_UserPlaceListCollaborators_EnforceRelationshipRules" on public."UserPlaceListCollaborators"';
    execute 'create trigger "TR_UserPlaceListCollaborators_EnforceRelationshipRules" before insert or update of "UserPlaceListId", "UserId", "IsActive" on public."UserPlaceListCollaborators" for each row execute function public."EnforceCollectionCollaboratorRelationshipRules"()';
  end if;
end;
$$;

create or replace function public."GetMySessionUserId"()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select u."UserId"
  from public."Users" u
  where u."AuthUserId" = auth.uid()
    and coalesce(u."AccountStatus", 'ACTIVE') <> 'DELETED'
  limit 1;
$$;

revoke all on function public."GetMySessionUserId"() from public;
grant execute on function public."GetMySessionUserId"() to authenticated, service_role;

create or replace function public."GetMyUserRelationshipState"(
  p_target_user_id integer
)
returns table (
  "IsBlockedByMe" boolean,
  "IsBlockedByThem" boolean,
  "IsMutedByMe" boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMySessionUserId"();
begin
  if v_user_id is null then
    raise exception 'Oturum kullanıcısı bulunamadı.';
  end if;

  return query
  select
    exists (
      select 1
      from public."UserBlocks" b
      where b."BlockerUserId" = v_user_id
        and b."BlockedUserId" = p_target_user_id
        and b."IsActive" = true
    ),
    exists (
      select 1
      from public."UserBlocks" b
      where b."BlockerUserId" = p_target_user_id
        and b."BlockedUserId" = v_user_id
        and b."IsActive" = true
    ),
    exists (
      select 1
      from public."UserMutes" m
      where m."MuterUserId" = v_user_id
        and m."MutedUserId" = p_target_user_id
        and m."IsActive" = true
    );
end;
$$;

create or replace function public."GetMyUnavailableUserIds"()
returns table ("UserId" integer)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select public."GetMySessionUserId"() as "UserId"
  )
  select b."BlockedUserId"
  from public."UserBlocks" b, me
  where b."BlockerUserId" = me."UserId"
    and b."IsActive" = true
  union
  select b."BlockerUserId"
  from public."UserBlocks" b, me
  where b."BlockedUserId" = me."UserId"
    and b."IsActive" = true;
$$;

create or replace function public."GetMyMutedUserIds"()
returns table ("UserId" integer)
language sql
stable
security definer
set search_path = public
as $$
  select m."MutedUserId"
  from public."UserMutes" m
  where m."MuterUserId" = public."GetMySessionUserId"()
    and m."IsActive" = true;
$$;

create or replace function public."GetMyBlockedUsers"()
returns table (
  "UserId" integer,
  "Username" varchar,
  "FirstName" varchar,
  "LastName" varchar,
  "ProfilePhotoPath" text,
  "CreatedDate" timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    u."UserId",
    u."Username"::varchar,
    u."FirstName"::varchar,
    u."LastName"::varchar,
    u."ProfilePhotoPath"::text,
    b."CreatedDate"
  from public."UserBlocks" b
  join public."Users" u on u."UserId" = b."BlockedUserId"
  where b."BlockerUserId" = public."GetMySessionUserId"()
    and b."IsActive" = true
  order by b."CreatedDate" desc;
$$;

create or replace function public."GetMyMutedUsers"()
returns table (
  "UserId" integer,
  "Username" varchar,
  "FirstName" varchar,
  "LastName" varchar,
  "ProfilePhotoPath" text,
  "CreatedDate" timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    u."UserId",
    u."Username"::varchar,
    u."FirstName"::varchar,
    u."LastName"::varchar,
    u."ProfilePhotoPath"::text,
    m."CreatedDate"
  from public."UserMutes" m
  join public."Users" u on u."UserId" = m."MutedUserId"
  where m."MuterUserId" = public."GetMySessionUserId"()
    and m."IsActive" = true
  order by m."CreatedDate" desc;
$$;

create or replace function public."MuteUser"(p_muted_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
begin
  if p_muted_user_id is null or p_muted_user_id = v_user_id then
    raise exception 'Geçersiz kullanıcı.';
  end if;

  if exists (
    select 1 from public."UserBlocks" b
    where b."IsActive" = true
      and ((b."BlockerUserId" = v_user_id and b."BlockedUserId" = p_muted_user_id)
        or (b."BlockerUserId" = p_muted_user_id and b."BlockedUserId" = v_user_id))
  ) then
    raise exception 'Engellenmiş kullanıcı sessize alınamaz.';
  end if;

  if not exists (
    select 1
    from public."GetExternalUserProfile"(p_muted_user_id) as target_profile
    where target_profile."FollowStatusCode" = 'ACCEPTED'
  ) then
    raise exception 'Yalnızca takip ettiğin kullanıcıları sessize alabilirsin.';
  end if;

  update public."UserMutes"
  set "IsActive" = true,
      "CreatedDate" = now(),
      "UpdatedDate" = now()
  where "MuterUserId" = v_user_id
    and "MutedUserId" = p_muted_user_id;

  if not found then
    insert into public."UserMutes" (
      "MuterUserId", "MutedUserId", "IsActive", "CreatedDate"
    ) values (
      v_user_id, p_muted_user_id, true, now()
    );
  end if;

  update public."Notifications"
  set "IsActive" = false
  where "RecipientUserId" = v_user_id
    and "ActorUserId" = p_muted_user_id
    and "IsActive" = true
    and "NotificationTypeCode" in (
      'FOLLOWING_NOTE',
      'NOTE_REACTION_UP',
      'NOTE_REACTION_DOWN'
    );
end;
$$;

create or replace function public."UnmuteUser"(p_muted_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMySessionUserId"();
  v_muted_since timestamptz;
begin
  select m."CreatedDate"
  into v_muted_since
  from public."UserMutes" m
  where m."MuterUserId" = v_user_id
    and m."MutedUserId" = p_muted_user_id
    and m."IsActive" = true
  order by m."CreatedDate" desc
  limit 1;

  update public."UserMutes"
  set "IsActive" = false, "UpdatedDate" = now()
  where "MuterUserId" = v_user_id
    and "MutedUserId" = p_muted_user_id
    and "IsActive" = true;

  if v_muted_since is not null then
    update public."Notifications"
    set "IsActive" = false
    where "RecipientUserId" = v_user_id
      and "ActorUserId" = p_muted_user_id
      and "CreatedDate" >= v_muted_since
      and "NotificationTypeCode" in (
        'FOLLOWING_NOTE',
        'NOTE_REACTION_UP',
        'NOTE_REACTION_DOWN'
      );
  end if;
end;
$$;

create or replace function public."RemoveFollower"(p_follower_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
begin
  update public."UserFollows"
  set "IsActive" = false,
      "UpdatedDate" = now()
  where "FollowerUserId" = p_follower_user_id
    and "FollowingUserId" = v_user_id
    and "IsActive" = true;
end;
$$;

create or replace function public."BlockUser"(p_blocked_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
begin
  if p_blocked_user_id is null or p_blocked_user_id = v_user_id then
    raise exception 'Geçersiz kullanıcı.';
  end if;

  if not exists (
    select 1
    from public."Users" u
    where u."UserId" = p_blocked_user_id
      and u."IsActive" = true
      and coalesce(u."AccountStatus", 'ACTIVE') = 'ACTIVE'
  ) then
    raise exception 'Kullanıcı bulunamadı.';
  end if;

  update public."UserBlocks"
  set "IsActive" = true, "UpdatedDate" = now()
  where "BlockerUserId" = v_user_id
    and "BlockedUserId" = p_blocked_user_id;

  if not found then
    insert into public."UserBlocks" (
      "BlockerUserId", "BlockedUserId", "IsActive", "CreatedDate"
    ) values (
      v_user_id, p_blocked_user_id, true, now()
    );
  end if;

  update public."UserMutes"
  set "IsActive" = false, "UpdatedDate" = now()
  where "IsActive" = true
    and (("MuterUserId" = v_user_id and "MutedUserId" = p_blocked_user_id)
      or ("MuterUserId" = p_blocked_user_id and "MutedUserId" = v_user_id));

  update public."UserFollows"
  set "IsActive" = false,
      "UpdatedDate" = now()
  where "IsActive" = true
    and (("FollowerUserId" = v_user_id and "FollowingUserId" = p_blocked_user_id)
      or ("FollowerUserId" = p_blocked_user_id and "FollowingUserId" = v_user_id));

  if to_regclass('public."PlaceNoteReactions"') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'PlaceNoteReactions'
         and column_name in ('PlaceNoteId', 'UserId', 'IsActive')
       group by table_schema, table_name
       having count(*) = 3
     ) then
    execute $sql$
      update public."PlaceNoteReactions" reaction
      set "IsActive" = false,
          "UpdatedDate" = now()
      from public."PlaceNotes" note_row
      where reaction."PlaceNoteId" = note_row."PlaceNoteId"
        and reaction."IsActive" = true
        and ((reaction."UserId" = $1 and note_row."UserId" = $2)
          or (reaction."UserId" = $2 and note_row."UserId" = $1))
    $sql$ using v_user_id, p_blocked_user_id;
  end if;

  update public."Notifications"
  set "IsActive" = false
  where "IsActive" = true
    and (("RecipientUserId" = v_user_id and "ActorUserId" = p_blocked_user_id)
      or ("RecipientUserId" = p_blocked_user_id and "ActorUserId" = v_user_id));

  -- Collaborative collection schema changed during earlier releases. Handle the
  -- current UserPlaceListId/UserId layout only when those columns are present.
  if to_regclass('public."UserPlaceListCollaborators"') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'UserPlaceListCollaborators'
         and column_name = 'UserId'
     ) then
    execute $sql$
      update public."UserPlaceListCollaborators" c
      set "IsActive" = false
      from public."UserPlaceLists" l
      where c."UserPlaceListId" = l."UserPlaceListId"
        and c."IsActive" = true
        and ((l."UserId" = $1 and c."UserId" = $2)
          or (l."UserId" = $2 and c."UserId" = $1))
    $sql$ using v_user_id, p_blocked_user_id;
  end if;
end;
$$;

create or replace function public."UnblockUser"(p_blocked_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public."UserBlocks"
  set "IsActive" = false, "UpdatedDate" = now()
  where "BlockerUserId" = public."GetMySessionUserId"()
    and "BlockedUserId" = p_blocked_user_id
    and "IsActive" = true;
end;
$$;

create or replace function public."SetMyAccountVisibility"(p_is_private boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer := public."GetMyActiveUserId"();
  v_visibility_id integer;
begin
  select s."AccountVisibilityStatusId"
  into v_visibility_id
  from public."AccountVisibilityStatuses" s
  where upper(s."Code") = case when p_is_private then 'PRIVATE' else 'PUBLIC' end
    and s."IsActive" = true
  limit 1;

  if v_visibility_id is null then
    raise exception 'Hesap görünürlük durumu bulunamadı.';
  end if;

  update public."Users"
  set "AccountVisibilityStatusId" = v_visibility_id,
      "UpdatedDate" = now()
  where "UserId" = v_user_id;
end;
$$;

create or replace function public."PurgeUserAccountData"(p_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public."Users" u
    where u."UserId" = p_user_id
      and u."AccountStatus" = 'DELETION_PENDING'
      and u."ScheduledDeletionDate" <= now()
  ) then
    raise exception 'Silinmeye hazır hesap bulunamadı.';
  end if;

  update public."Notifications"
  set "IsActive" = false
  where "RecipientUserId" = p_user_id or "ActorUserId" = p_user_id;

  update public."UserFollows"
  set "IsActive" = false, "UpdatedDate" = now()
  where "FollowerUserId" = p_user_id or "FollowingUserId" = p_user_id;

  delete from public."UserMutes"
  where "MuterUserId" = p_user_id or "MutedUserId" = p_user_id;

  delete from public."UserBlocks"
  where "BlockerUserId" = p_user_id or "BlockedUserId" = p_user_id;

  if to_regclass('public."WebPushSubscriptions"') is not null then
    execute 'update public."WebPushSubscriptions" set "IsActive" = false, "UpdatedDate" = now() where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."UserWebPushPreferences"') is not null then
    execute 'delete from public."UserWebPushPreferences" where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."PlaceNoteReactions"') is not null then
    execute 'update public."PlaceNoteReactions" set "IsActive" = false, "UpdatedDate" = now() where "UserId" = $1'
    using p_user_id;
  end if;

  if to_regclass('public."UserPlaceListCollaborators"') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'UserPlaceListCollaborators'
         and column_name = 'UserId'
     ) then
    execute 'update public."UserPlaceListCollaborators" set "IsActive" = false where "UserId" = $1'
    using p_user_id;
  end if;

  update public."PlaceNotes"
  set "IsActive" = false, "UpdatedDate" = now()
  where "UserId" = p_user_id and "IsActive" = true;

  update public."UserPlaceLists"
  set "IsActive" = false, "UpdatedDate" = now()
  where "UserId" = p_user_id and "IsActive" = true;

  update public."Users"
  set "ProfilePhotoPath" = null,
      "DeletionAuthUserId" = coalesce("DeletionAuthUserId", "AuthUserId"),
      "AuthUserId" = null,
      "UpdatedDate" = now()
  where "UserId" = p_user_id;
end;
$$;

create or replace function public."CompleteUserAccountDeletion"(p_user_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public."Users"
  set "AuthUserId" = null,
      "DeletionAuthUserId" = null,
      "Username" = left('deleted_' || "UserId"::text || '_' || substr(md5(random()::text), 1, 8), 30),
      "Email" = 'deleted+' || "UserId"::text || '@invalid.local',
      "FirstName" = 'Silinmiş Hesap',
      "LastName" = null,
      "ProfilePhotoPath" = null,
      "AccountStatus" = 'DELETED',
      "IsActive" = false,
      "FrozenDate" = null,
      "DeletionRequestedDate" = null,
      "ScheduledDeletionDate" = null,
      "UpdatedDate" = now()
  where "UserId" = p_user_id;
end;
$$;

-- A user can only read their own relationship rows. All writes go through RPCs.
drop policy if exists "UserBlocks_SelectOwn" on public."UserBlocks";
create policy "UserBlocks_SelectOwn"
on public."UserBlocks"
for select
to authenticated
using (
  "BlockerUserId" = public."GetMySessionUserId"()
  or "BlockedUserId" = public."GetMySessionUserId"()
);

drop policy if exists "UserMutes_SelectOwn" on public."UserMutes";
create policy "UserMutes_SelectOwn"
on public."UserMutes"
for select
to authenticated
using ("MuterUserId" = public."GetMySessionUserId"());

revoke all on table public."UserBlocks" from anon, authenticated;
revoke all on table public."UserMutes" from anon, authenticated;
grant select on table public."UserBlocks" to authenticated, service_role;
grant select on table public."UserMutes" to authenticated, service_role;
grant all on table public."UserBlocks" to service_role;
grant all on table public."UserMutes" to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public."EnforceUserFollowRelationshipRules"() from public;
revoke all on function public."ClearMuteWhenFollowEnds"() from public;
revoke all on function public."ApplyNotificationRelationshipRules"() from public;
revoke all on function public."EnforceNoteReactionRelationshipRules"() from public;
revoke all on function public."EnforceCollectionCollaboratorRelationshipRules"() from public;
revoke all on function public."GetMyUserRelationshipState"(integer) from public;
revoke all on function public."GetMyUnavailableUserIds"() from public;
revoke all on function public."GetMyMutedUserIds"() from public;
revoke all on function public."GetMyBlockedUsers"() from public;
revoke all on function public."GetMyMutedUsers"() from public;
revoke all on function public."MuteUser"(integer) from public;
revoke all on function public."UnmuteUser"(integer) from public;
revoke all on function public."RemoveFollower"(integer) from public;
revoke all on function public."BlockUser"(integer) from public;
revoke all on function public."UnblockUser"(integer) from public;
revoke all on function public."SetMyAccountVisibility"(boolean) from public;
revoke all on function public."PurgeUserAccountData"(integer) from public;
revoke all on function public."CompleteUserAccountDeletion"(integer) from public;

grant execute on function public."GetMyUserRelationshipState"(integer) to authenticated;
grant execute on function public."GetMyUnavailableUserIds"() to authenticated;
grant execute on function public."GetMyMutedUserIds"() to authenticated;
grant execute on function public."GetMyBlockedUsers"() to authenticated;
grant execute on function public."GetMyMutedUsers"() to authenticated;
grant execute on function public."MuteUser"(integer) to authenticated;
grant execute on function public."UnmuteUser"(integer) to authenticated;
grant execute on function public."RemoveFollower"(integer) to authenticated;
grant execute on function public."BlockUser"(integer) to authenticated;
grant execute on function public."UnblockUser"(integer) to authenticated;
grant execute on function public."SetMyAccountVisibility"(boolean) to authenticated;
grant execute on function public."PurgeUserAccountData"(integer) to service_role;
grant execute on function public."CompleteUserAccountDeletion"(integer) to service_role;

commit;
